#!/usr/bin/bash 
python -u run.py --train \
    --optim adam \
    --eval_freq 10 \
    --check_point 6400 \
    --dataset VK \
    --combine exp_mul \
    --use_gnn \
    --gnn_neigh_sample 5 \
    --gnn_concat False \
    --gnn_dropout 0.5 \
    --inter_neigh_sample 0 \
    --learning_rate 0.001 \
    --lr_decay 0.5 \
    --weight_decay 1e-5 \
    --dropout_rate 0.45 \
    --num_steps 6400 \
    --embed_size 128 \
    --hidden_size 32 \
    --batch_size 128 \
    --patience 2 \
    --model_dir ./GraphCM/models/ \
    --result_dir ./GraphCM/results/ \
    --summary_dir ./GraphCM/summary/ \
    --log_dir ./GraphCM/log/
